image: gitpod/workspace-base

tasks:
- name: install mamba, meryl, merqury, get data
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n mer -c bioconda merqury -y
    mamba activate mer
    wget https://github.com/marbl/meryl/releases/download/v1.4.1/meryl-1.4.1.Linux-amd64.tar.xz
    tar xJf meryl-1.4.1.Linux-amd64.tar.xz

    cd /workspace
    curl -L https://genomeark.s3.amazonaws.com/trainingmaterials/BGA2023/Merqury/data.tar.gz | tar xzf -

  command: |
    mv /workspace/merqury /workspace/merqury-bga23
    git clone https://github.com/marbl/merqury.git
    cd merqury
    export MERQURY=$PWD
    export PATH=$PWD:/workspace/meryl-1.4.1/bin/:$PATH
    cd /workspace

    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate mer
    
    clear

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
