image: gitpod/workspace-base

tasks:
- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n mer -c bioconda merqury -y
    mamba activate mer
    wget https://github.com/marbl/meryl/releases/download/v1.4.1/meryl-1.4.1.Linux-amd64.tar.xz
    tar xJf meryl-1.4.1.Linux-amd64.tar.xz
    export PATH=/workspace/meryl-1.4.1/bin/:$PATH
    clear

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
