image: gitpod/workspace-base

tasks:
- name: install mamba
  command: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash

    source ${HOME}/.bashrc

    mamba create -n mer -c bioconda merqury meryl=1.4 -y
    mamba activate mer

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
